# Fish completion for inir CLI
# Install: inir completions install fish
# Or: inir completions fish > ~/.config/fish/completions/inir.fish

# The words after `inir`, `inir ipc` or `inir bind <keys>`: an IPC call being typed.
function __inir_call_words
    set -l words (commandline -opc)
    set -e words[1]
    if test (count $words) -ge 1; and test "$words[1]" = ipc
        set -e words[1]
    else if test (count $words) -ge 1; and test "$words[1]" = bind
        set -e words[1]
        while test (count $words) -ge 1; and string match -q -- '--*' "$words[1]"
            set -e words[1]
        end
        # The keys come first; with none typed yet there is no call.
        test (count $words) -ge 1; or return 1
        set -e words[1]
    end
    test (count $words) -gt 0; and printf '%s\n' $words
    return 0
end
# Nothing of the call typed yet: offer the targets.
function __inir_at_target
    set -l words (commandline -opc)
    if test (count $words) -ge 2; and not contains -- "$words[2]" ipc bind
        return 1
    end
    set -l w (__inir_call_words); or return 1
    test (count $w) -eq 0
end
# The target typed: offer its functions.
function __inir_at_function
    set -l w (__inir_call_words); or return 1
    test (count $w) -eq 1; and contains -- "$w[1]" $argv
end
# Target and function typed: offer the values it knows for each of its arguments.
function __inir_at_value -a nargs fn
    set -l targets $argv[3..-1]
    set -l w (__inir_call_words); or return 1
    test (count $w) -ge 2; and test (count $w) -le (math 1 + $nargs); and contains -- "$w[1]" $targets; and test "$w[2]" = "$fn"
end

complete -c inir -f

# CLI commands
complete -c inir -n '__fish_use_subcommand' -a install -d 'Install iNiR'
complete -c inir -n '__fish_use_subcommand' -a start -d 'Start the shell'
complete -c inir -n '__fish_use_subcommand' -a stop -d 'Stop the shell'
complete -c inir -n '__fish_use_subcommand' -a run -d 'Run the shell'
complete -c inir -n '__fish_use_subcommand' -a restart -d 'Restart the shell'
complete -c inir -n '__fish_use_subcommand' -a kill -d 'Kill the shell process'
complete -c inir -n '__fish_use_subcommand' -a logs -d 'View runtime logs'
complete -c inir -n '__fish_use_subcommand' -a terminal -d 'Open terminal'
complete -c inir -n '__fish_use_subcommand' -a browser -d 'Open browser'
complete -c inir -n '__fish_use_subcommand' -a close-window -d 'Close focused window'
complete -c inir -n '__fish_use_subcommand' -a ipc -d 'Low-level IPC call'
complete -c inir -n '__fish_use_subcommand' -a settings -d 'Toggle settings'
complete -c inir -n '__fish_use_subcommand' -a settings-window -d 'Open settings window'
complete -c inir -n '__fish_use_subcommand' -a waffle-settings-window -d 'Open waffle settings'
complete -c inir -n '__fish_use_subcommand' -a repair -d 'Repair shell state'
complete -c inir -n '__fish_use_subcommand' -a path -d 'Show config path'
complete -c inir -n '__fish_use_subcommand' -a test-local -d 'Run local tests'
complete -c inir -n '__fish_use_subcommand' -a setup -d 'Run setup directly'
complete -c inir -n '__fish_use_subcommand' -a service -d 'Manage systemd service'
complete -c inir -n '__fish_use_subcommand' -a doctor -d 'Health checks'
complete -c inir -n '__fish_use_subcommand' -a migrate -d 'Run migrations'
complete -c inir -n '__fish_use_subcommand' -a status -d 'Shell status'
complete -c inir -n '__fish_use_subcommand' -a update -d 'Update shell'
complete -c inir -n '__fish_use_subcommand' -a rollback -d 'Rollback update'
complete -c inir -n '__fish_use_subcommand' -a my-changes -d 'Show local changes'
complete -c inir -n '__fish_use_subcommand' -a uninstall -d 'Uninstall shell'
complete -c inir -n '__fish_use_subcommand' -a config -d 'View/edit config'
complete -c inir -n '__fish_use_subcommand' -a info -d 'System info'
complete -c inir -n '__fish_use_subcommand' -a backup -d 'Create backup'
complete -c inir -n '__fish_use_subcommand' -a version -d 'Show version'
complete -c inir -n '__fish_use_subcommand' -a theme -d 'Theme management'
complete -c inir -n '__fish_use_subcommand' -a help -d 'Show help'
complete -c inir -n '__fish_use_subcommand' -a completions -d 'Generate shell completions'
complete -c inir -n '__fish_use_subcommand' -a bind -d 'Make a Niri keybind for any inir call'

# Subcommand completions: service
complete -c inir -n '__fish_seen_subcommand_from service' -a 'install uninstall enable disable start stop restart status logs'

# Subcommand completions: theme
complete -c inir -n '__fish_seen_subcommand_from theme' -a 'list-targets inspect doctor scaffold apply'

# Subcommand completions: completions
complete -c inir -n '__fish_seen_subcommand_from completions' -a 'bash zsh fish install'

# Subcommand completions: bind (keys first, then any call)
complete -c inir -n '__fish_seen_subcommand_from bind; and test (count (commandline -opc)) -eq 2' -a '--add --remove --list --examples' -d 'bind option'

# >>> generated from the IPC registry: python3 scripts/lib/generate-ipc-registry.py >>>
complete -c inir -n '__inir_at_target' -a ai -d 'Shared multi-provider AI service'
complete -c inir -n '__inir_at_function ai' -a ensureInitialized -d 'Force-load models, provider catalogs and API keys'
complete -c inir -n '__inir_at_function ai' -a diagnose -d 'Dump current AI, catalog and tool state as JSON'
complete -c inir -n '__inir_at_function ai' -a refreshCatalog -d 'Refresh every live provider model catalog'
complete -c inir -n '__inir_at_function ai' -a catalog -d 'Search up to 100 normalized live model records'
complete -c inir -n '__inir_at_function ai' -a providers -d 'Return provider health, key state and live model counts'
complete -c inir -n '__inir_at_function ai' -a run -d 'Send a message or compatibility /command to AI chat'
complete -c inir -n '__inir_at_function ai' -a runGet -d 'Run an AI command and return the last response'
complete -c inir -n '__inir_at_target' -a altSwitcher -d 'Alt+Tab window switcher'
complete -c inir -n '__inir_at_target' -a alt-switcher -d 'Alt+Tab window switcher'
complete -c inir -n '__inir_at_function altSwitcher alt-switcher' -a opens -d 'Which switcher Alt+Tab opens: inir, niri (Niri\'s own Recent…'
complete -c inir -n '__inir_at_value 1 opens altSwitcher alt-switcher' -a 'inir niri status'
complete -c inir -n '__inir_at_function altSwitcher alt-switcher' -a open -d 'Open switcher'
complete -c inir -n '__inir_at_function altSwitcher alt-switcher' -a close -d 'Close switcher'
complete -c inir -n '__inir_at_function altSwitcher alt-switcher' -a toggle -d 'Toggle switcher'
complete -c inir -n '__inir_at_function altSwitcher alt-switcher' -a next -d 'Focus next window'
complete -c inir -n '__inir_at_function altSwitcher alt-switcher' -a previous -d 'Focus previous window'
complete -c inir -n '__inir_at_target' -a appCatalog -d 'App catalog service'
complete -c inir -n '__inir_at_target' -a app-catalog -d 'App catalog service'
complete -c inir -n '__inir_at_function appCatalog app-catalog' -a refresh -d 'Refresh the installed-state cache'
complete -c inir -n '__inir_at_function appCatalog app-catalog' -a search -d 'Filter catalog entries by query'
complete -c inir -n '__inir_at_function appCatalog app-catalog' -a install -d 'Install app by catalog ID'
complete -c inir -n '__inir_at_function appCatalog app-catalog' -a list -d 'List catalog apps with install status and descriptions'
complete -c inir -n '__inir_at_target' -a audio -d 'Volume and mute control'
complete -c inir -n '__inir_at_function audio' -a volumeUp -d 'Increase volume'
complete -c inir -n '__inir_at_function audio' -a volumeDown -d 'Decrease volume'
complete -c inir -n '__inir_at_function audio' -a mute -d 'Toggle speaker mute'
complete -c inir -n '__inir_at_function audio' -a playEvent -d 'Play a shell event sound (e.g'
complete -c inir -n '__inir_at_value 1 playEvent audio' -a 'batteryLow timerDone'
complete -c inir -n '__inir_at_function audio' -a micMute -d 'Toggle microphone mute'
complete -c inir -n '__inir_at_target' -a autostart -d 'Niri login autostart manager'
complete -c inir -n '__inir_at_function autostart' -a status -d 'Return niri\\'
complete -c inir -n '__inir_at_function autostart' -a addCommand -d 'Append a managed spawn-sh-at-startup shell line'
complete -c inir -n '__inir_at_value 1 addCommand autostart' -a 'spawn-sh-at-startup'
complete -c inir -n '__inir_at_function autostart' -a addApp -d 'Append a managed gtk-launch <desktopId> entry'
complete -c inir -n '__inir_at_function autostart' -a removeLast -d 'Remove the last managed entry'
complete -c inir -n '__inir_at_function autostart' -a reload -d 'Force re-read the startup file'
complete -c inir -n '__inir_at_target' -a background -d 'Desktop background and widget controls'
complete -c inir -n '__inir_at_function background' -a widgetDesign -d 'Put every desktop widget on iris, material, individual, ins…'
complete -c inir -n '__inir_at_value 1 widgetDesign background' -a 'iris material individual instrument readout undo status'
complete -c inir -n '__inir_at_function background' -a widgetMaterial -d 'iRiS: status reports the shared widget material and how man…'
complete -c inir -n '__inir_at_value 1 widgetMaterial background' -a 'status match'
complete -c inir -n '__inir_at_function background' -a widgetSearch -d 'While arranging (iRiS), find a widget from the bar: the wor…'
complete -c inir -n '__inir_at_value 1 widgetSearch background' -a 'open next previous take close'
complete -c inir -n '__inir_at_function background' -a toggleEditMode -d 'Toggle widget edit mode (drag, resize, configure desktop wi…'
complete -c inir -n '__inir_at_function background' -a toggleWidgetManager -d 'Enter edit mode if needed and toggle the widget manager on…'
complete -c inir -n '__inir_at_function background' -a setEditMode -d 'Set widget edit mode explicitly'
complete -c inir -n '__inir_at_function background' -a editState -d 'Report the active selection, physical panel insets, full de…'
complete -c inir -n '__inir_at_function background' -a applyOrganicEdgePreset -d 'Apply an Organic Edge scene by name without changing enable…'
complete -c inir -n '__inir_at_function background' -a applyOrganicEdgeComposition -d 'Apply only an Organic Edge topology/geometry preset'
complete -c inir -n '__inir_at_function background' -a applyOrganicEdgeMaterial -d 'Apply only an Organic Edge material/light preset'
complete -c inir -n '__inir_at_function background' -a applyOrganicEdgeResponse -d 'Apply only an Organic Edge music-response preset'
complete -c inir -n '__inir_at_function background' -a organicEdgeState -d 'Report each Organic Edge output, selected edges, frame, aud…'
complete -c inir -n '__inir_at_function background' -a setOrganicEdgeEnabled -d 'Enable or disable the independent Organic Edge screen field'
complete -c inir -n '__inir_at_function background' -a quickControlsPage -d 'Show a page of the selected widget\'s quick controls: widget…'
complete -c inir -n '__inir_at_function background' -a quickControlsGeometry -d 'Report where the selected widget\'s toolbar and quick-contro…'
complete -c inir -n '__inir_at_function background' -a widgetSnapshot -d 'Save one desktop widget, as it renders now, to a PNG (offsc…'
complete -c inir -n '__inir_at_function background' -a legibilityState -d 'Report what each desktop widget reads under itself (brightn…'
complete -c inir -n '__inir_at_function background' -a desktopItemsState -d 'Report desktop-item persistence, availability, item count,…'
complete -c inir -n '__inir_at_function background' -a focusWidget -d 'Select a desktop widget and optionally open its quick contr…'
complete -c inir -n '__inir_at_function background' -a promoteWidget -d 'Move a desktop widget to the top of the persistent layer or…'
complete -c inir -n '__inir_at_function background' -a resetLayerOrder -d 'Reset desktop widgets to their built-in stacking order'
complete -c inir -n '__inir_at_function background' -a setWidgetEnabled -d 'Enable or disable a built-in desktop widget'
complete -c inir -n '__inir_at_function background' -a clockDebugState -d 'Report clock palette, renderer and quick-control geometry d…'
complete -c inir -n '__inir_at_function background' -a clockDebugSetMode -d 'cookie adaptToWallpaper'
complete -c inir -n '__inir_at_function background' -a clockDebugSetRegion -d 'Inject a temporary wallpaper-region sample'
complete -c inir -n '__inir_at_function background' -a clockDebugSetLayout -d 'Probe quick-control geometry at a hypothetical clock positi…'
complete -c inir -n '__inir_at_function background' -a clockDebugRestore -d 'Restore the config captured by clock diagnostics'
complete -c inir -n '__inir_at_target' -a bar -d 'Top bar visibility'
complete -c inir -n '__inir_at_function bar' -a mediaWidth -d 'How wide the song title gets in Material\'s bar, 120 to 640…'
complete -c inir -n '__inir_at_function bar' -a toggle -d 'Show/hide bar'
complete -c inir -n '__inir_at_function bar' -a close -d 'Hide bar'
complete -c inir -n '__inir_at_function bar' -a open -d 'Show bar'
complete -c inir -n '__inir_at_target' -a battery -d 'The laptop battery as every family shows it'
complete -c inir -n '__inir_at_function battery' -a status -d 'Print the level and whether it is charging, discharging or…'
complete -c inir -n '__inir_at_function battery' -a simulate -d 'Pretend the battery is at a level and state until the shell…'
complete -c inir -n '__inir_at_value 1 simulate battery' -a 'full off'
complete -c inir -n '__inir_at_target' -a bluetooth -d 'The Bluetooth adapter as every family shows it'
complete -c inir -n '__inir_at_function bluetooth' -a status -d 'Print on, off, no adapter or how many devices are connected…'
complete -c inir -n '__inir_at_function bluetooth' -a simulate -d 'Pretend the adapter is off, on, has a number of connected d…'
complete -c inir -n '__inir_at_value 1 simulate bluetooth' -a 'off on none clear'
complete -c inir -n '__inir_at_target' -a brightness -d 'Display brightness control'
complete -c inir -n '__inir_at_function brightness' -a increment -d 'Increase brightness'
complete -c inir -n '__inir_at_function brightness' -a decrement -d 'Decrease brightness'
complete -c inir -n '__inir_at_function brightness' -a refresh -d 'Re-read every output\'s level from the hardware (after the m…'
complete -c inir -n '__inir_at_function brightness' -a set -d 'Set the focused output\'s brightness, the same path as the s…'
complete -c inir -n '__inir_at_function brightness' -a status -d 'Each output: how it is driven (DDC bus or backlight), the s…'
complete -c inir -n '__inir_at_function brightness' -a sleepBegin -d 'sleepBegin'
complete -c inir -n '__inir_at_function brightness' -a restoreAfterWake -d 'restoreAfterWake'
complete -c inir -n '__inir_at_target' -a cheatsheet -d 'Keyboard shortcuts reference'
complete -c inir -n '__inir_at_function cheatsheet' -a toggle -d 'Open/close cheatsheet'
complete -c inir -n '__inir_at_function cheatsheet' -a close -d 'Hide cheatsheet overlay'
complete -c inir -n '__inir_at_function cheatsheet' -a open -d 'Show cheatsheet overlay'
complete -c inir -n '__inir_at_target' -a clipboard -d 'Clipboard history panel'
complete -c inir -n '__inir_at_function clipboard' -a open -d 'Open panel'
complete -c inir -n '__inir_at_function clipboard' -a close -d 'Close panel'
complete -c inir -n '__inir_at_function clipboard' -a toggle -d 'Open/close panel'
complete -c inir -n '__inir_at_target' -a cliphistService -d 'Clipboard history service'
complete -c inir -n '__inir_at_target' -a cliphist-service -d 'Clipboard history service'
complete -c inir -n '__inir_at_function cliphistService cliphist-service' -a update -d 'Refresh clipboard history'
complete -c inir -n '__inir_at_target' -a closeConfirm -d 'Close window confirmation dialog'
complete -c inir -n '__inir_at_target' -a close-confirm -d 'Close window confirmation dialog'
complete -c inir -n '__inir_at_function closeConfirm close-confirm' -a trigger -d 'Show close confirmation for focused window'
complete -c inir -n '__inir_at_function closeConfirm close-confirm' -a triggerWindow -d 'Close or confirm the exact window captured by inir close-wi…'
complete -c inir -n '__inir_at_function closeConfirm close-confirm' -a close -d 'Dismiss the dialog without closing'
complete -c inir -n '__inir_at_target' -a colorMode -d 'The system\'s light or dark mode, the one the shell and your…'
complete -c inir -n '__inir_at_target' -a color-mode -d 'The system\'s light or dark mode, the one the shell and your…'
complete -c inir -n '__inir_at_function colorMode color-mode' -a set -d 'dark, light or toggle'
complete -c inir -n '__inir_at_value 1 set colorMode color-mode' -a 'dark light toggle'
complete -c inir -n '__inir_at_function colorMode color-mode' -a get -d 'JSON: the mode in use, the colour theme, the saved choice,…'
complete -c inir -n '__inir_at_target' -a connections -d 'Short notices when something is plugged in, connected, unpl…'
complete -c inir -n '__inir_at_function connections' -a sample -d 'Show how a notice looks without plugging anything: network,…'
complete -c inir -n '__inir_at_value 1 sample connections' -a 'network internet bluetooth usb power audio displays drives'
complete -c inir -n '__inir_at_function connections' -a status -d 'Print which kinds are on as JSON, and whether udev is there…'
complete -c inir -n '__inir_at_function connections' -a enable -d 'enable'
complete -c inir -n '__inir_at_function connections' -a disable -d 'disable'
complete -c inir -n '__inir_at_function connections' -a toggle -d 'toggle'
complete -c inir -n '__inir_at_target' -a controlPanel -d 'Quick settings panel'
complete -c inir -n '__inir_at_target' -a control-panel -d 'Quick settings panel'
complete -c inir -n '__inir_at_function controlPanel control-panel' -a toggle -d 'Open/close control panel'
complete -c inir -n '__inir_at_function controlPanel control-panel' -a close -d 'Close control panel'
complete -c inir -n '__inir_at_function controlPanel control-panel' -a open -d 'Open control panel'
complete -c inir -n '__inir_at_target' -a coverflowSelector -d 'Wallpaper coverflow (3D card) picker'
complete -c inir -n '__inir_at_target' -a coverflow-selector -d 'Wallpaper coverflow (3D card) picker'
complete -c inir -n '__inir_at_function coverflowSelector coverflow-selector' -a toggle -d 'Open/close coverflow selector'
complete -c inir -n '__inir_at_function coverflowSelector coverflow-selector' -a open -d 'Open coverflow selector'
complete -c inir -n '__inir_at_function coverflowSelector coverflow-selector' -a close -d 'Close coverflow selector'
complete -c inir -n '__inir_at_target' -a customWidgets -d 'Custom widget management'
complete -c inir -n '__inir_at_target' -a custom-widgets -d 'Custom widget management'
complete -c inir -n '__inir_at_function customWidgets custom-widgets' -a reload -d 'Re-scan widgets directory and reload all custom widgets'
complete -c inir -n '__inir_at_function customWidgets custom-widgets' -a list -d 'List all discovered custom widgets (JSON output)'
complete -c inir -n '__inir_at_function customWidgets custom-widgets' -a create -d 'Create a new widget scaffold in the widgets directory'
complete -c inir -n '__inir_at_function customWidgets custom-widgets' -a remove -d 'Remove a custom widget by ID'
complete -c inir -n '__inir_at_target' -a dashboard -d 'Centered welcome hub panel (ii family): greeting, clock, no…'
complete -c inir -n '__inir_at_function dashboard' -a toggle -d 'Open/close dashboard'
complete -c inir -n '__inir_at_function dashboard' -a close -d 'Close dashboard'
complete -c inir -n '__inir_at_function dashboard' -a open -d 'Open dashboard'
complete -c inir -n '__inir_at_target' -a dev -d 'Development navigation for loading lazy surfaces and intern…'
complete -c inir -n '__inir_at_function dev' -a list -d 'Return the destination inventory as JSON'
complete -c inir -n '__inir_at_function dev' -a open -d 'Open a destination by semantic identifier'
complete -c inir -n '__inir_at_function dev' -a close -d 'Close development-opened surfaces and clear the request'
complete -c inir -n '__inir_at_function dev' -a reload -d 'Reload the shell\'s QML the way an edit does (soft: windows…'
complete -c inir -n '__inir_at_function dev' -a current -d 'Return the current destination or closed'
complete -c inir -n '__inir_at_function dev' -a meter -d 'Measure frame gaps for the given milliseconds (250–20000, d…'
complete -c inir -n '__inir_at_function dev' -a metered -d 'Return the last measurement as JSON: frames, mean, p95, wor…'
complete -c inir -n '__inir_at_function dev' -a dragSim -d 'Simulate carrying an iRiS bubble (slot id, default extra-cl…'
complete -c inir -n '__inir_at_value 2 dragSim dev' -a 'extra-clock'
complete -c inir -n '__inir_at_function dev' -a dropBubble -d 'dropBubble'
complete -c inir -n '__inir_at_function dev' -a dockSlide -d 'dockSlide'
complete -c inir -n '__inir_at_target' -a equalizer -d 'Open the ii-family EasyEffects output equalizer'
complete -c inir -n '__inir_at_function equalizer' -a toggle -d 'Open/close equalizer'
complete -c inir -n '__inir_at_function equalizer' -a close -d 'Hide equalizer'
complete -c inir -n '__inir_at_function equalizer' -a open -d 'Show equalizer'
complete -c inir -n '__inir_at_function equalizer' -a refresh -d 'Refresh EasyEffects equalizer state'
complete -c inir -n '__inir_at_function equalizer' -a ensure -d 'Ensure Equalizer control is available; bootstraps a neutral…'
complete -c inir -n '__inir_at_function equalizer' -a status -d 'Return current equalizer state as JSON'
complete -c inir -n '__inir_at_function equalizer' -a setBand -d 'Set one 0-based band gain in dB'
complete -c inir -n '__inir_at_function equalizer' -a preset -d 'Apply one built-in EQ preset'
complete -c inir -n '__inir_at_function equalizer' -a configure -d 'Convert the active Equalizer to the iNiR 10-band layout'
complete -c inir -n '__inir_at_target' -a gamemode -d 'Performance mode for gaming'
complete -c inir -n '__inir_at_function gamemode' -a toggle -d 'Toggle gamemode on/off'
complete -c inir -n '__inir_at_function gamemode' -a activate -d 'Force enable gamemode'
complete -c inir -n '__inir_at_function gamemode' -a deactivate -d 'Force disable gamemode'
complete -c inir -n '__inir_at_function gamemode' -a status -d 'Print current gamemode state (e.g'
complete -c inir -n '__inir_at_target' -a globalActions -d 'Command palette / action registry'
complete -c inir -n '__inir_at_target' -a global-actions -d 'Command palette / action registry'
complete -c inir -n '__inir_at_function globalActions global-actions' -a run -d 'Execute action by ID (e.g'
complete -c inir -n '__inir_at_function globalActions global-actions' -a runWithArgs -d 'runWithArgs'
complete -c inir -n '__inir_at_function globalActions global-actions' -a list -d 'List all actions, optionally filtered by category'
complete -c inir -n '__inir_at_function globalActions global-actions' -a search -d 'Fuzzy search actions by name/description/keywords'
complete -c inir -n '__inir_at_function globalActions global-actions' -a open -d 'Open the overview in action mode'
complete -c inir -n '__inir_at_target' -a globalStyle -d 'The Global Style every Material surface and desktop widget…'
complete -c inir -n '__inir_at_target' -a global-style -d 'The Global Style every Material surface and desktop widget…'
complete -c inir -n '__inir_at_function globalStyle global-style' -a set -d 'Switch to a style by name, with its bar corner and card def…'
complete -c inir -n '__inir_at_function globalStyle global-style' -a get -d 'Return the active style'
complete -c inir -n '__inir_at_function globalStyle global-style' -a list -d 'List the styles'
complete -c inir -n '__inir_at_target' -a iris -d 'iRiS bar and Island design'
complete -c inir -n '__inir_at_function iris' -a open -d 'Expand the island on the focused output'
complete -c inir -n '__inir_at_function iris' -a page -d 'Expand the island on a page: media, activity, desktop, tray…'
complete -c inir -n '__inir_at_value 1 page iris' -a 'media activity desktop tray tools next prev'
complete -c inir -n '__inir_at_function iris' -a close -d 'Collapse the island'
complete -c inir -n '__inir_at_function iris' -a toggle -d 'Expand or collapse the island on the focused output'
complete -c inir -n '__inir_at_function iris' -a card -d 'open, close or toggle the media bubble\'s floating card, or…'
complete -c inir -n '__inir_at_value 1 card iris' -a 'open close toggle pin'
complete -c inir -n '__inir_at_function iris' -a theme -d 'iRiS themes, each a whole redesign of the family: list, app…'
complete -c inir -n '__inir_at_value 1 theme iris' -a 'list apply: save: import: export export: folder'
complete -c inir -n '__inir_at_function iris' -a settings -d 'Open iRiS Settings on a section: general, appearance, motio…'
complete -c inir -n '__inir_at_value 1 settings iris' -a 'general appearance motion bar bubbles dock desktop windows sidebars controlCenter spotlight orbit notifications sound capture display keyboard battery gaming lock player anime sources system lock/security next prev back forward search: open'
complete -c inir -n '__inir_at_function iris' -a bubble -d 'Place an Island bubble (left, right, utility) or an extra b…'
complete -c inir -n '__inir_at_value 2 bubble iris' -a 'left right utility weather notifications controls sound mic tools media visualizer tray top-left top-right bottom-left bottom-right'
complete -c inir -n '__inir_at_function iris' -a dock -d 'reveal, hide or toggle the iRiS Dock (revealed stays until…'
complete -c inir -n '__inir_at_value 1 dock iris' -a 'reveal hide toggle'
complete -c inir -n '__inir_at_function iris' -a dockApp -d 'Open a Dock app\'s windows or menu by app id (e.g'
complete -c inir -n '__inir_at_value 2 dockApp iris' -a 'windows menu pin'
complete -c inir -n '__inir_at_function iris' -a dockMove -d 'Move a Dock app to a position, counting icons from 1 with t…'
complete -c inir -n '__inir_at_function iris' -a appBubble -d 'Carry a Dock app out as a bubble of its own (e.g'
complete -c inir -n '__inir_at_value 2 appBubble iris' -a 'dock'
complete -c inir -n '__inir_at_function iris' -a focus -d 'open, close or toggle the Focus panel (the left one), and s…'
complete -c inir -n '__inir_at_value 1 focus iris' -a 'open close toggle'
complete -c inir -n '__inir_at_function iris' -a today -d 'open, close or toggle the Today panel (the right one), and…'
complete -c inir -n '__inir_at_value 1 today iris' -a 'open close toggle'
complete -c inir -n '__inir_at_function iris' -a controlCenter -d 'open, close or toggle the Control Center, and say whether i…'
complete -c inir -n '__inir_at_value 1 controlCenter iris' -a 'open close toggle'
complete -c inir -n '__inir_at_function iris' -a pin -d 'Keep the left (Focus) or right (Today) panel open beside wi…'
complete -c inir -n '__inir_at_value 1 pin iris' -a 'left right'
complete -c inir -n '__inir_at_function iris' -a layout -d 'How the Island sits on its edge: island, left, right, full…'
complete -c inir -n '__inir_at_value 1 layout iris' -a 'island left right full menubar'
complete -c inir -n '__inir_at_function iris' -a strip -d 'What the menu bar lays under its items: transparent (on the…'
complete -c inir -n '__inir_at_value 1 strip iris' -a 'transparent band'
complete -c inir -n '__inir_at_function iris' -a edge -d 'Move the Island to a screen edge: top, bottom, left or righ…'
complete -c inir -n '__inir_at_value 1 edge iris' -a 'top bottom left right'
complete -c inir -n '__inir_at_function iris' -a dockEdge -d 'Move the Dock: auto (opposite the Island), top, bottom, lef…'
complete -c inir -n '__inir_at_value 1 dockEdge iris' -a 'auto top bottom left right'
complete -c inir -n '__inir_at_function iris' -a zone -d 'What a full-width Island carries in a zone: start, center o…'
complete -c inir -n '__inir_at_value 2 zone iris' -a 'start center end island workspaces window time none'
complete -c inir -n '__inir_at_function iris' -a barPiece -d 'Turn one of the Island\'s own pieces on or off: weather, not…'
complete -c inir -n '__inir_at_value 2 barPiece iris' -a 'weather notifications controls sound mic tools media visualizer tray on off toggle'
complete -c inir -n '__inir_at_function iris' -a arrange -d 'Arrange the Island\'s desktop page in place — move, remove a…'
complete -c inir -n '__inir_at_value 1 arrange iris' -a 'on off toggle'
complete -c inir -n '__inir_at_function iris' -a edit -d 'Customize iRiS on the shell itself: the Island grows a caps…'
complete -c inir -n '__inir_at_value 1 edit iris' -a 'on off toggle themes pieces material colour type motion bodies places transients desktop island dock vitals left'
complete -c inir -n '__inir_at_function iris' -a studio -d 'Customize as a panel beside the screen (Studio): on, off, t…'
complete -c inir -n '__inir_at_value 1 studio iris' -a 'on off toggle material colour type motion island pieces bodies places transients dock desktop themes search:'
complete -c inir -n '__inir_at_function iris' -a notch -d 'Melt the Island into its edge (or into the Surround band):…'
complete -c inir -n '__inir_at_value 1 notch iris' -a 'on off toggle'
complete -c inir -n '__inir_at_function iris' -a surround -d 'Close the shell around the screen with a band on every edge…'
complete -c inir -n '__inir_at_value 1 surround iris' -a 'on off toggle'
complete -c inir -n '__inir_at_function iris' -a accent -d 'Set iRiS accent: blue, mint, rose, lilac or wallpaper'
complete -c inir -n '__inir_at_value 1 accent iris' -a 'blue mint rose lilac wallpaper'
complete -c inir -n '__inir_at_function iris' -a spotlight -d 'Open Spotlight with a query already typed, e.g'
complete -c inir -n '__inir_at_function iris' -a gallerySource -d 'Show or hide an online source in the wallpaper gallery: wal…'
complete -c inir -n '__inir_at_value 2 gallerySource iris' -a 'wallhaven live konachan yandere on off toggle'
complete -c inir -n '__inir_at_function iris' -a orbit -d 'Open Orbit with a search already typed, e.g'
complete -c inir -n '__inir_at_function iris' -a orbitCorner -d 'The corner each output\'s Orbit hot corner is on right now,…'
complete -c inir -n '__inir_at_function iris' -a orbitClose -d 'Close Orbit'
complete -c inir -n '__inir_at_function iris' -a spotlightClose -d 'Close Spotlight'
complete -c inir -n '__inir_at_function iris' -a bubbleCard -d 'Grow a bubble\'s own card: weather, notifications, sound, mi…'
complete -c inir -n '__inir_at_value 1 bubbleCard iris' -a 'weather notifications sound mic tools tray close'
complete -c inir -n '__inir_at_function iris' -a tap -d 'Tap a piece the Island carries (controls, sound, tray, noti…'
complete -c inir -n '__inir_at_value 1 tap iris' -a 'controls sound tray notifications weather'
complete -c inir -n '__inir_at_function iris' -a bubbleMenu -d 'Open a floating bubble\'s own menu — what it opens, where it…'
complete -c inir -n '__inir_at_value 1 bubbleMenu iris' -a 'weather sound'
complete -c inir -n '__inir_at_function iris' -a morph -d 'Set how iRiS morphs: direct, liquid, glide, snap, elastic o…'
complete -c inir -n '__inir_at_value 1 morph iris' -a 'direct liquid glide snap elastic instant'
complete -c inir -n '__inir_at_function iris' -a activity -d 'Publish a live activity into the Island from any script: <a…'
complete -c inir -n '__inir_at_value 3 activity iris' -a 'title progress detail glyph tint blue sky teal green yellow orange red pink indigo purple lavender gray'
complete -c inir -n '__inir_at_function iris' -a activities -d 'Return the live activities scripts have published, as JSON'
complete -c inir -n '__inir_at_function iris' -a set -d 'Set any iRiS option by path, e.g'
complete -c inir -n '__inir_at_function iris' -a adaptive -d 'How much the wallpaper shapes iRiS, 0-100; any other word p…'
complete -c inir -n '__inir_at_function iris' -a tokens -d 'JSON with the colours iRiS resolved for the current look an…'
complete -c inir -n '__inir_at_function iris' -a palette -d 'The colour theme the shell and your apps wear: an id such a…'
complete -c inir -n '__inir_at_value 1 palette iris' -a 'catppuccin-mocha iris-ink auto list current'
complete -c inir -n '__inir_at_function iris' -a preset -d 'Set the iRiS appearance preset: iris, soft, round, crisp, a…'
complete -c inir -n '__inir_at_value 1 preset iris' -a 'iris soft round crisp angular contrast'
complete -c inir -n '__inir_at_function iris' -a icon -d 'Choose the glyph a piece wears: controls, tools, focus, not…'
complete -c inir -n '__inir_at_value 2 icon iris' -a 'controls tools focus notifications bluetooth updates anime watching reset'
complete -c inir -n '__inir_at_function iris' -a control -d 'Arrange the Control Center in place (drag controls, resize…'
complete -c inir -n '__inir_at_value 1 control iris' -a 'edit done toggle undo'
complete -c inir -n '__inir_at_function iris' -a lock -d 'Rehearse the lock screen (the real surface, editable, with…'
complete -c inir -n '__inir_at_value 1 lock iris' -a 'edit done toggle page: layouts scene type clock widgets widget: weather monthCalendar select: iris centered corner minimal'
complete -c inir -n '__inir_at_function iris' -a utility -d 'Set the utility satellite: tray, tools, sound, mic or none'
complete -c inir -n '__inir_at_value 1 utility iris' -a 'tray tools sound mic none'
complete -c inir -n '__inir_at_function iris' -a watch -d 'What the Continue bubble has in progress, or resume one of…'
complete -c inir -n '__inir_at_function iris' -a watchPick -d 'Answer whatever the Continue bubble is asking (which show,…'
complete -c inir -n '__inir_at_value 1 watchPick iris' -a 'cancel'
complete -c inir -n '__inir_at_function iris' -a desktopAction -d 'Run a desktop menu entry on the focused output as a click w…'
complete -c inir -n '__inir_at_value 1 desktopAction iris' -a 'wallpaper wallpaperNext nextWallpaper terminal screenshot'
complete -c inir -n '__inir_at_function iris' -a desktopMenu -d 'Open the desktop menu on the focused output at that point,…'
complete -c inir -n '__inir_at_function iris' -a menuClose -d 'Close whichever iRiS or shell context menu is open'
complete -c inir -n '__inir_at_function iris' -a watchSubs -d 'Subtitles of the episode that is playing: size+, size- (kep…'
complete -c inir -n '__inir_at_value 1 watchSubs iris' -a 'size+ size- delay+ delay- delay0 off track: file:'
complete -c inir -n '__inir_at_function iris' -a watchSeek -d 'Jump inside the episode that is playing by seconds: 85 skip…'
complete -c inir -n '__inir_at_function iris' -a watchSkip -d 'Close the episode that is playing and start the next (defau…'
complete -c inir -n '__inir_at_value 1 watchSkip iris' -a 'next previous'
complete -c inir -n '__inir_at_function iris' -a motion -d 'Measure how a Place opens, closes and reverses halfway, fro…'
complete -c inir -n '__inir_at_value 1 motion iris' -a 'spotlight orbit gallery settings focus today card motioned'
complete -c inir -n '__inir_at_function iris' -a motioned -d 'The last motion measurement as JSON: frame pace, continuity…'
complete -c inir -n '__inir_at_function iris' -a status -d 'JSON with the Island, Dock, Control Center, Spotlight and s…'
complete -c inir -n '__inir_at_target' -a keyboard -d 'Keyboard layout switching (Niri only)'
complete -c inir -n '__inir_at_function keyboard' -a switchLayout -d 'Switch to next keyboard layout'
complete -c inir -n '__inir_at_function keyboard' -a switchLayoutPrevious -d 'Switch to previous keyboard layout'
complete -c inir -n '__inir_at_function keyboard' -a getCurrentLayout -d 'Get the current layout name'
complete -c inir -n '__inir_at_function keyboard' -a getLayouts -d 'Get all configured layout names (JSON array)'
complete -c inir -n '__inir_at_target' -a lock -d 'Lock screen'
complete -c inir -n '__inir_at_function lock' -a activate -d 'Lock the screen'
complete -c inir -n '__inir_at_function lock' -a prepareSleep -d 'Suspend handshake: activate immediately and wait until the…'
complete -c inir -n '__inir_at_function lock' -a deactivate -d 'Cancel lock and mark screen unlocked'
complete -c inir -n '__inir_at_function lock' -a status -d 'Return lock state (secure, locked, activating, or unlocked)'
complete -c inir -n '__inir_at_function lock' -a focus -d 'Refocus the lock screen input'
complete -c inir -n '__inir_at_target' -a loginScreen -d 'The login screen you see after starting the computer'
complete -c inir -n '__inir_at_target' -a login-screen -d 'The login screen you see after starting the computer'
complete -c inir -n '__inir_at_function loginScreen login-screen' -a set -d 'auto (iRiS while you use iRiS, Classic otherwise), classic…'
complete -c inir -n '__inir_at_value 1 set loginScreen login-screen' -a 'auto classic iris'
complete -c inir -n '__inir_at_function loginScreen login-screen' -a style -d 'How the iRiS login is composed: cover (your picture sharp,…'
complete -c inir -n '__inir_at_value 1 style loginScreen login-screen' -a 'cover frame lens'
complete -c inir -n '__inir_at_function loginScreen login-screen' -a status -d 'Print the choice and the look it gives (e.g'
complete -c inir -n '__inir_at_function loginScreen login-screen' -a sync -d 'Copy the current colours, wallpaper and style to the login…'
complete -c inir -n '__inir_at_target' -a mascot -d 'Playful mascot companion (needs mascot.enable and the compa…'
complete -c inir -n '__inir_at_function mascot' -a poke -d 'Ask her to peek from a random edge with a random pose'
complete -c inir -n '__inir_at_function mascot' -a status -d 'Return JSON diagnostics for mood, configured/effective voic…'
complete -c inir -n '__inir_at_function mascot' -a setVoice -d 'Set the idle voice register to adaptive, casual, dry, compo…'
complete -c inir -n '__inir_at_value 1 setVoice mascot' -a 'adaptive casual dry composed chaotic'
complete -c inir -n '__inir_at_function mascot' -a romp -d 'Chaos mode: she runs across the desktop and bonks a widget,…'
complete -c inir -n '__inir_at_function mascot' -a chase -d 'Chase game: she hunts your mouse, every click is a spot she…'
complete -c inir -n '__inir_at_function mascot' -a hideSeek -d 'Hide-and-seek: she tucks into a spot on the desktop'
complete -c inir -n '__inir_at_function mascot' -a tidy -d 'Undo the chaos: every displaced widget returns to its pre-c…'
complete -c inir -n '__inir_at_function mascot' -a appear -d 'Show a specific catalog pose from left, right, top or bottom'
complete -c inir -n '__inir_at_value 2 appear mascot' -a 'left right top bottom'
complete -c inir -n '__inir_at_function mascot' -a appearContextual -d 'Show near the triggering widget (battery, media, update, ne…'
complete -c inir -n '__inir_at_value 2 appearContextual mascot' -a 'battery media update network dnd mascot.companion.contextualPlacement'
complete -c inir -n '__inir_at_function mascot' -a appearWithLine -d 'Show a specific pose saying an exact line (used by the bar…'
complete -c inir -n '__inir_at_function mascot' -a hide -d 'Dismiss the peek or active chaos, cancel follow-ups, tidy w…'
complete -c inir -n '__inir_at_function mascot' -a snooze -d 'Dismiss Kira and pause automatic visits for 1–480 minutes'
complete -c inir -n '__inir_at_target' -a mascotMood -d 'Session-long mood state that flavors the mascot\'s idle line…'
complete -c inir -n '__inir_at_target' -a mascot-mood -d 'Session-long mood state that flavors the mascot\'s idle line…'
complete -c inir -n '__inir_at_function mascotMood mascot-mood' -a set -d 'Force a mood: neutral, sleepy, hyper, snarky or contemplati…'
complete -c inir -n '__inir_at_value 1 set mascotMood mascot-mood' -a 'neutral sleepy hyper snarky contemplative'
complete -c inir -n '__inir_at_function mascotMood mascot-mood' -a current -d 'Print the current mood'
complete -c inir -n '__inir_at_target' -a mediaControls -d 'Floating media controls panel'
complete -c inir -n '__inir_at_target' -a media-controls -d 'Floating media controls panel'
complete -c inir -n '__inir_at_function mediaControls media-controls' -a toggle -d 'Open/close media controls'
complete -c inir -n '__inir_at_function mediaControls media-controls' -a close -d 'Hide media controls'
complete -c inir -n '__inir_at_function mediaControls media-controls' -a open -d 'Show media controls'
complete -c inir -n '__inir_at_target' -a memory -d 'Memory pressure monitoring for JSGCHeap accumulation (Qt V4…'
complete -c inir -n '__inir_at_function memory' -a collect -d 'Force JavaScript garbage collection'
complete -c inir -n '__inir_at_function memory' -a stats -d 'Return JSON with deleted mappings count, threshold, and sta…'
complete -c inir -n '__inir_at_function memory' -a restart -d 'Restart the shell to free accumulated memory'
complete -c inir -n '__inir_at_function memory' -a dismiss -d 'Dismiss the memory warning notification'
complete -c inir -n '__inir_at_function memory' -a reset -d 'Reset notification state (re-enables warnings)'
complete -c inir -n '__inir_at_target' -a minimize -d 'Window minimization (Niri workaround - moves windows to hid…'
complete -c inir -n '__inir_at_function minimize' -a minimize -d 'Minimize focused window'
complete -c inir -n '__inir_at_function minimize' -a minimizeId -d 'Minimize a window by Niri window ID'
complete -c inir -n '__inir_at_function minimize' -a restore -d 'Restore a minimized window by ID'
complete -c inir -n '__inir_at_function minimize' -a restoreOriginal -d 'Restore a minimized window to the workspace it came from'
complete -c inir -n '__inir_at_target' -a mpris -d 'Media player control'
complete -c inir -n '__inir_at_function mpris' -a pauseAll -d 'Pause all players'
complete -c inir -n '__inir_at_function mpris' -a playPause -d 'Toggle play/pause (uses YtMusic if active)'
complete -c inir -n '__inir_at_function mpris' -a previous -d 'Previous track (uses YtMusic if active)'
complete -c inir -n '__inir_at_function mpris' -a next -d 'Next track (uses YtMusic if active)'
complete -c inir -n '__inir_at_function mpris' -a select -d 'Hand the controls to another player: next, prev, or part of…'
complete -c inir -n '__inir_at_value 1 select mpris' -a 'next prev spotify firefox'
complete -c inir -n '__inir_at_target' -a network -d 'Whether the shell can reach the internet, as NetworkManager…'
complete -c inir -n '__inir_at_function network' -a status -d 'Print the state as JSON: online, connectivity (full, limite…'
complete -c inir -n '__inir_at_function network' -a check -d 'Ask NetworkManager to check connectivity again, for example…'
complete -c inir -n '__inir_at_function network' -a simulate -d 'Pretend the connectivity is none, limited, portal or full u…'
complete -c inir -n '__inir_at_value 1 simulate network' -a 'none limited portal full'
complete -c inir -n '__inir_at_function network' -a simulateLink -d 'Pretend the link is "wifi 40" (a signal strength), searchin…'
complete -c inir -n '__inir_at_value 1 simulateLink network' -a 'searching connecting ethernet none off'
complete -c inir -n '__inir_at_target' -a niriAnimations -d 'Presets for Niri\'s own window, workspace and overview anima…'
complete -c inir -n '__inir_at_target' -a niri-animations -d 'Presets for Niri\'s own window, workspace and overview anima…'
complete -c inir -n '__inir_at_function niriAnimations niri-animations' -a list -d 'List the presets;  marks the one your config matches'
complete -c inir -n '__inir_at_function niriAnimations niri-animations' -a active -d 'Print the preset your config matches, or custom after hand…'
complete -c inir -n '__inir_at_function niriAnimations niri-animations' -a apply -d 'Apply a preset: snappy, niri, material, bouncy, gentle, ins…'
complete -c inir -n '__inir_at_value 1 apply niriAnimations niri-animations' -a 'snappy niri material bouncy gentle instant'
complete -c inir -n '__inir_at_target' -a notifications -d 'Notification management'
complete -c inir -n '__inir_at_function notifications' -a test -d 'Send test notifications'
complete -c inir -n '__inir_at_function notifications' -a clearAll -d 'Dismiss all notifications'
complete -c inir -n '__inir_at_function notifications' -a toggleSilent -d 'Toggle Do Not Disturb mode'
complete -c inir -n '__inir_at_function notifications' -a invokeAction -d 'Press a button on the newest notification that has it, as a…'
complete -c inir -n '__inir_at_target' -a orbit -d 'Niri-only session navigator'
complete -c inir -n '__inir_at_function orbit' -a toggle -d 'Open/close Orbit'
complete -c inir -n '__inir_at_function orbit' -a close -d 'Close Orbit if it is active'
complete -c inir -n '__inir_at_function orbit' -a open -d 'Open Orbit on the focused output'
complete -c inir -n '__inir_at_function orbit' -a pocket -d 'Open Orbit directly into Pocket'
complete -c inir -n '__inir_at_function orbit' -a studio -d 'Open Orbit directly into the live Studio editor'
complete -c inir -n '__inir_at_function orbit' -a find -d 'Open Orbit Focus Lens and filter session windows by app or…'
complete -c inir -n '__inir_at_function orbit' -a stage -d 'Open Orbit in the classic Stage view for this session'
complete -c inir -n '__inir_at_function orbit' -a orbital -d 'Open Orbit in the Orbital workspace view for this session'
complete -c inir -n '__inir_at_function orbit' -a next -d 'Switch Niri to the next workspace while Orbit stays open'
complete -c inir -n '__inir_at_function orbit' -a previous -d 'Switch Niri to the previous workspace while Orbit stays open'
complete -c inir -n '__inir_at_function orbit' -a status -d 'Print the effective Orbit runtime state used by diagnostics…'
complete -c inir -n '__inir_at_function orbit' -a toggleView -d 'Switch the open Orbit session between Stage and Orbital'
complete -c inir -n '__inir_at_target' -a osd -d 'On-screen feedback for any family'
complete -c inir -n '__inir_at_function osd' -a volume -d 'Show the volume level'
complete -c inir -n '__inir_at_function osd' -a brightness -d 'Show the brightness level'
complete -c inir -n '__inir_at_function osd' -a mic -d 'Show the microphone level'
complete -c inir -n '__inir_at_function osd' -a keyboard -d 'Show the keyboard layout'
complete -c inir -n '__inir_at_function osd' -a media -d 'Show now playing with a transport action: play, pause, next…'
complete -c inir -n '__inir_at_value 1 media osd' -a 'play pause next previous'
complete -c inir -n '__inir_at_function osd' -a hide -d 'Hide whatever is showing'
complete -c inir -n '__inir_at_target' -a osdVolume -d 'On-screen volume indicator'
complete -c inir -n '__inir_at_target' -a osd-volume -d 'On-screen volume indicator'
complete -c inir -n '__inir_at_function osdVolume osd-volume' -a trigger -d 'Show volume OSD'
complete -c inir -n '__inir_at_function osdVolume osd-volume' -a hide -d 'Hide volume OSD'
complete -c inir -n '__inir_at_function osdVolume osd-volume' -a toggle -d 'Toggle volume OSD'
complete -c inir -n '__inir_at_target' -a osk -d 'On-screen keyboard'
complete -c inir -n '__inir_at_function osk' -a toggle -d 'Show/hide on-screen keyboard'
complete -c inir -n '__inir_at_function osk' -a close -d 'Hide on-screen keyboard'
complete -c inir -n '__inir_at_function osk' -a open -d 'Show on-screen keyboard'
complete -c inir -n '__inir_at_target' -a overlay -d 'Floating tools (Super+G): notes, images, crosshair, recorde…'
complete -c inir -n '__inir_at_function overlay' -a toggle -d 'Open/close Floating tools'
complete -c inir -n '__inir_at_function overlay' -a tool -d 'Show or hide one floating tool by id (crosshair, fpsLimiter…'
complete -c inir -n '__inir_at_value 2 tool overlay' -a 'crosshair fpsLimiter floatingImage recorder resources notes discord volumeMixer notifications gamePerformance on off toggle'
complete -c inir -n '__inir_at_target' -a overview -d 'Toggle the workspace overview panel'
complete -c inir -n '__inir_at_function overview' -a toggle -d 'Open/close overview'
complete -c inir -n '__inir_at_function overview' -a close -d 'Close overview'
complete -c inir -n '__inir_at_function overview' -a open -d 'Open overview'
complete -c inir -n '__inir_at_function overview' -a toggleReleaseInterrupt -d 'Clear the super-key release interrupt flag'
complete -c inir -n '__inir_at_function overview' -a clipboardToggle -d 'Open clipboard search, or close if already open'
complete -c inir -n '__inir_at_function overview' -a actionOpen -d 'Open overview in action search mode'
complete -c inir -n '__inir_at_target' -a packageSearch -d 'Package search service'
complete -c inir -n '__inir_at_target' -a package-search -d 'Package search service'
complete -c inir -n '__inir_at_function packageSearch package-search' -a search -d 'Start a package search'
complete -c inir -n '__inir_at_function packageSearch package-search' -a results -d 'Print current search results'
complete -c inir -n '__inir_at_target' -a panelFamily -d 'Switch between the three shell families: Material ii (defau…'
complete -c inir -n '__inir_at_target' -a panel-family -d 'Switch between the three shell families: Material ii (defau…'
complete -c inir -n '__inir_at_function panelFamily panel-family' -a cycle -d 'Switch to the next family in the switch list (familyCycle,…'
complete -c inir -n '__inir_at_function panelFamily panel-family' -a set -d 'Set specific family ("ii", "waffle", or "iris")'
complete -c inir -n '__inir_at_target' -a pill -d 'The pill bar\'s morphing surfaces (only registered while Bar…'
complete -c inir -n '__inir_at_function pill' -a open -d 'Open a surface by name on the focused monitor'
complete -c inir -n '__inir_at_function pill' -a close -d 'Close the open surface'
complete -c inir -n '__inir_at_function pill' -a toggle -d 'Open a surface, or close it if already open'
complete -c inir -n '__inir_at_function pill' -a state -d 'Print the open surface name, or closed'
complete -c inir -n '__inir_at_target' -a recordingOsd -d 'Screen recording floating pill OSD'
complete -c inir -n '__inir_at_target' -a recording-osd -d 'Screen recording floating pill OSD'
complete -c inir -n '__inir_at_function recordingOsd recording-osd' -a toggle -d 'Stop the current recording (if active)'
complete -c inir -n '__inir_at_function recordingOsd recording-osd' -a show -d 'Reveal the recording OSD pill'
complete -c inir -n '__inir_at_function recordingOsd recording-osd' -a hide -d 'Collapse/hide the recording OSD pill'
complete -c inir -n '__inir_at_target' -a region -d 'Region selection tools'
complete -c inir -n '__inir_at_function region' -a screenshot -d 'Take a rectangular region screenshot'
complete -c inir -n '__inir_at_function region' -a search -d 'Image search (Google Lens)'
complete -c inir -n '__inir_at_function region' -a googleLens -d 'Start a region capture for Google Lens'
complete -c inir -n '__inir_at_function region' -a ocr -d 'OCR text recognition'
complete -c inir -n '__inir_at_function region' -a record -d 'Record region (no audio)'
complete -c inir -n '__inir_at_function region' -a recordWithSound -d 'Record region with audio'
complete -c inir -n '__inir_at_function region' -a menu -d 'Open the unified snip menu, optionally restoring its last t…'
complete -c inir -n '__inir_at_function region' -a dismiss -d 'Close the selector overlay'
complete -c inir -n '__inir_at_function region' -a current -d 'Return the selector state (open/action/mode) as JSON'
complete -c inir -n '__inir_at_target' -a search -d 'Waffle start menu / search'
complete -c inir -n '__inir_at_function search' -a toggle -d 'Open/close start menu'
complete -c inir -n '__inir_at_function search' -a close -d 'Close start menu'
complete -c inir -n '__inir_at_function search' -a open -d 'Open start menu'
complete -c inir -n '__inir_at_target' -a session -d 'Power menu'
complete -c inir -n '__inir_at_function session' -a toggle -d 'Open/close session menu'
complete -c inir -n '__inir_at_function session' -a close -d 'Hide session screen'
complete -c inir -n '__inir_at_function session' -a open -d 'Show session screen'
complete -c inir -n '__inir_at_target' -a settings -d 'Open or toggle the settings window'
complete -c inir -n '__inir_at_function settings' -a open -d 'Open the settings window'
complete -c inir -n '__inir_at_function settings' -a toggle -d 'Toggle settings in the active host (overlay or window)'
complete -c inir -n '__inir_at_function settings' -a openOverlay -d 'Switch to overlay mode and open Settings'
complete -c inir -n '__inir_at_function settings' -a openOverlayAt -d 'Switch to overlay mode, open Settings and preserve/jump to…'
complete -c inir -n '__inir_at_value 1 openOverlayAt settings' -a 'index'
complete -c inir -n '__inir_at_function settings' -a openWindowAt -d 'Switch to standalone Window mode and open page index'
complete -c inir -n '__inir_at_value 1 openWindowAt settings' -a 'index'
complete -c inir -n '__inir_at_function settings' -a setOverlayStyle -d 'Switch overlay chrome while preserving page index'
complete -c inir -n '__inir_at_value 2 setOverlayStyle settings' -a 'index'
complete -c inir -n '__inir_at_target' -a settingsNav -d 'Navigate the settings overlay to a specific page (same as c…'
complete -c inir -n '__inir_at_target' -a settings-nav -d 'Navigate the settings overlay to a specific page (same as c…'
complete -c inir -n '__inir_at_function settingsNav settings-nav' -a page -d 'page'
complete -c inir -n '__inir_at_function settingsNav settings-nav' -a section -d 'section'
complete -c inir -n '__inir_at_function settingsNav settings-nav' -a count -d 'Number of settings pages'
complete -c inir -n '__inir_at_function settingsNav settings-nav' -a current -d 'Current page index, or -1 when no page is open'
complete -c inir -n '__inir_at_target' -a shellLayout -d 'Dedicated persistent-shell layout editing and diagnostics'
complete -c inir -n '__inir_at_target' -a shell-layout -d 'Dedicated persistent-shell layout editing and diagnostics'
complete -c inir -n '__inir_at_function shellLayout shell-layout' -a toggle -d 'Enter or leave shell edit mode'
complete -c inir -n '__inir_at_function shellLayout shell-layout' -a open -d 'Enter shell edit mode on the focused output'
complete -c inir -n '__inir_at_function shellLayout shell-layout' -a openOn -d 'Enter shell edit mode on a named output'
complete -c inir -n '__inir_at_function shellLayout shell-layout' -a close -d 'Leave shell edit mode and clear transient selection'
complete -c inir -n '__inir_at_function shellLayout shell-layout' -a select -d 'Select a surface for deterministic editing or diagnostics'
complete -c inir -n '__inir_at_function shellLayout shell-layout' -a lift -d 'Select and lift a surface for placement'
complete -c inir -n '__inir_at_function shellLayout shell-layout' -a preview -d 'Preview a legal slot without writing Config'
complete -c inir -n '__inir_at_function shellLayout shell-layout' -a place -d 'Commit the lifted surface to a validated slot; occupied sid…'
complete -c inir -n '__inir_at_function shellLayout shell-layout' -a cancel -d 'Cancel the current lift, preview, confirmation or gesture'
complete -c inir -n '__inir_at_function shellLayout shell-layout' -a dragStart -d 'Lift a surface and start a pointer-style drag'
complete -c inir -n '__inir_at_function shellLayout shell-layout' -a dragUpdate -d 'Feed screen coordinates to the active drag; previews the ne…'
complete -c inir -n '__inir_at_function shellLayout shell-layout' -a dragEnd -d 'Drop the dragged surface: commits the previewed edge (occup…'
complete -c inir -n '__inir_at_function shellLayout shell-layout' -a reset -d 'Restore one surface to its default placement and supported…'
complete -c inir -n '__inir_at_function shellLayout shell-layout' -a setProperty -d 'Set a supported surface property (sizeMode, sidebar height,…'
complete -c inir -n '__inir_at_value 3 setProperty shellLayout shell-layout' -a 'sizeMode height thickness'
complete -c inir -n '__inir_at_function shellLayout shell-layout' -a handleEscape -d 'Apply editor Escape priority: cancel pending work, then lea…'
complete -c inir -n '__inir_at_function shellLayout shell-layout' -a status -d 'Return edit-session, host diagnostics and active-family sur…'
complete -c inir -n '__inir_at_function shellLayout shell-layout' -a validate -d 'Validate a surface and slot combination without changing Co…'
complete -c inir -n '__inir_at_target' -a shellUpdate -d 'Shell update checker'
complete -c inir -n '__inir_at_target' -a shell-update -d 'Shell update checker'
complete -c inir -n '__inir_at_function shellUpdate shell-update' -a toggle -d 'Open/close update overlay'
complete -c inir -n '__inir_at_function shellUpdate shell-update' -a open -d 'Open update overlay'
complete -c inir -n '__inir_at_function shellUpdate shell-update' -a close -d 'Close update overlay'
complete -c inir -n '__inir_at_function shellUpdate shell-update' -a check -d 'Check for updates now'
complete -c inir -n '__inir_at_function shellUpdate shell-update' -a performUpdate -d 'Run the update'
complete -c inir -n '__inir_at_function shellUpdate shell-update' -a dismiss -d 'Dismiss update notification'
complete -c inir -n '__inir_at_function shellUpdate shell-update' -a undismiss -d 'Un-dismiss update notification'
complete -c inir -n '__inir_at_function shellUpdate shell-update' -a diagnose -d 'Dump update state as JSON'
complete -c inir -n '__inir_at_function shellUpdate shell-update' -a simulate -d 'on fakes a pending update to see the bubble, card and notif…'
complete -c inir -n '__inir_at_value 1 simulate shellUpdate shell-update' -a 'on off'
complete -c inir -n '__inir_at_target' -a sidebarLeft -d 'Left sidebar: AI chat and apps in Material; the customizabl…'
complete -c inir -n '__inir_at_target' -a sidebar-left -d 'Left sidebar: AI chat and apps in Material; the customizabl…'
complete -c inir -n '__inir_at_function sidebarLeft sidebar-left' -a toggle -d 'Open/close left sidebar'
complete -c inir -n '__inir_at_function sidebarLeft sidebar-left' -a close -d 'Hide left sidebar'
complete -c inir -n '__inir_at_function sidebarLeft sidebar-left' -a open -d 'Show left sidebar'
complete -c inir -n '__inir_at_function sidebarLeft sidebar-left' -a expand -d 'Open the sidebar in its wide Ctrl+O layout'
complete -c inir -n '__inir_at_function sidebarLeft sidebar-left' -a compact -d 'Return the sidebar to its normal width'
complete -c inir -n '__inir_at_function sidebarLeft sidebar-left' -a status -d 'Return open, expanded and detached state as JSON'
complete -c inir -n '__inir_at_function sidebarLeft sidebar-left' -a detach -d 'Move AI chat into its Ctrl+P standalone window'
complete -c inir -n '__inir_at_function sidebarLeft sidebar-left' -a attach -d 'Return AI chat from the standalone window to the sidebar'
complete -c inir -n '__inir_at_target' -a sidebarRight -d 'Right sidebar: quick toggles, notepad and settings in Mater…'
complete -c inir -n '__inir_at_target' -a sidebar-right -d 'Right sidebar: quick toggles, notepad and settings in Mater…'
complete -c inir -n '__inir_at_function sidebarRight sidebar-right' -a toggle -d 'Open/close right sidebar'
complete -c inir -n '__inir_at_function sidebarRight sidebar-right' -a close -d 'Hide right sidebar'
complete -c inir -n '__inir_at_function sidebarRight sidebar-right' -a open -d 'Show right sidebar'
complete -c inir -n '__inir_at_target' -a taskview -d 'Compatibility entry point for task navigation'
complete -c inir -n '__inir_at_function taskview' -a toggle -d 'Open/close the active family\'s task navigator'
complete -c inir -n '__inir_at_function taskview' -a close -d 'Close the active family\'s task navigator'
complete -c inir -n '__inir_at_function taskview' -a open -d 'Open the active family\'s task navigator'
complete -c inir -n '__inir_at_target' -a tiling -d 'Tiling layout overlay'
complete -c inir -n '__inir_at_function tiling' -a toggle -d 'Open/close tiling picker'
complete -c inir -n '__inir_at_function tiling' -a open -d 'Open tiling picker'
complete -c inir -n '__inir_at_function tiling' -a hide -d 'Close picker and OSD'
complete -c inir -n '__inir_at_function tiling' -a cycle -d 'Cycle to next tiling preset (shows OSD)'
complete -c inir -n '__inir_at_function tiling' -a showOsd -d 'Flash the current tiling preset OSD'
complete -c inir -n '__inir_at_function tiling' -a promote -d 'Promote focused window to master position'
complete -c inir -n '__inir_at_target' -a voiceSearch -d 'Provider-neutral voice input for web search and AI dictation'
complete -c inir -n '__inir_at_target' -a voice-search -d 'Provider-neutral voice input for web search and AI dictation'
complete -c inir -n '__inir_at_function voiceSearch voice-search' -a start -d 'Start recording for voice web search'
complete -c inir -n '__inir_at_function voiceSearch voice-search' -a stop -d 'Stop the active recording or transcription'
complete -c inir -n '__inir_at_function voiceSearch voice-search' -a toggle -d 'Toggle recording'
complete -c inir -n '__inir_at_function voiceSearch voice-search' -a refresh -d 'Re-detect local and connected speech backends'
complete -c inir -n '__inir_at_function voiceSearch voice-search' -a status -d 'Return backend, local detection, recording and error state…'
complete -c inir -n '__inir_at_target' -a vpn -d 'NetworkManager VPN profiles (OpenVPN, WireGuard, anything w…'
complete -c inir -n '__inir_at_function vpn' -a status -d 'Print the state as JSON: connected, through what, Tailscale…'
complete -c inir -n '__inir_at_function vpn' -a toggle -d 'Turn every active VPN off, or connect Tailscale (else your…'
complete -c inir -n '__inir_at_function vpn' -a details -d 'on, off or toggle the card\'s details: addresses, name, acco…'
complete -c inir -n '__inir_at_value 1 details vpn' -a 'on off toggle'
complete -c inir -n '__inir_at_function vpn' -a refresh -d 'Read profiles and Tailscale again'
complete -c inir -n '__inir_at_function vpn' -a importFile -d 'Add a WireGuard .conf or OpenVPN .ovpn file as a NetworkMan…'
complete -c inir -n '__inir_at_function vpn' -a add -d 'Create a VPN in NetworkManager\'s connection editor: wiregua…'
complete -c inir -n '__inir_at_value 1 add vpn' -a 'wireguard vpn nmtui'
complete -c inir -n '__inir_at_target' -a wactionCenter -d 'Waffle action center (quick settings)'
complete -c inir -n '__inir_at_target' -a waction-center -d 'Waffle action center (quick settings)'
complete -c inir -n '__inir_at_function wactionCenter waction-center' -a toggle -d 'Open/close action center'
complete -c inir -n '__inir_at_function wactionCenter waction-center' -a close -d 'Close action center'
complete -c inir -n '__inir_at_function wactionCenter waction-center' -a open -d 'Open action center'
complete -c inir -n '__inir_at_target' -a waffleAltSwitcher -d 'Waffle Alt+Tab window switcher'
complete -c inir -n '__inir_at_target' -a waffle-alt-switcher -d 'Waffle Alt+Tab window switcher'
complete -c inir -n '__inir_at_function waffleAltSwitcher waffle-alt-switcher' -a open -d 'Open switcher'
complete -c inir -n '__inir_at_function waffleAltSwitcher waffle-alt-switcher' -a close -d 'Close switcher'
complete -c inir -n '__inir_at_function waffleAltSwitcher waffle-alt-switcher' -a toggle -d 'Toggle switcher'
complete -c inir -n '__inir_at_function waffleAltSwitcher waffle-alt-switcher' -a next -d 'Focus next window'
complete -c inir -n '__inir_at_function waffleAltSwitcher waffle-alt-switcher' -a previous -d 'Focus previous window'
complete -c inir -n '__inir_at_target' -a wallpaperLauncher -d 'Navigation and apply controls for the compact wallpaper lau…'
complete -c inir -n '__inir_at_target' -a wallpaper-launcher -d 'Navigation and apply controls for the compact wallpaper lau…'
complete -c inir -n '__inir_at_function wallpaperLauncher wallpaper-launcher' -a next -d 'Select the next wallpaper'
complete -c inir -n '__inir_at_function wallpaperLauncher wallpaper-launcher' -a previous -d 'Select the previous wallpaper'
complete -c inir -n '__inir_at_function wallpaperLauncher wallpaper-launcher' -a applyCurrent -d 'Apply the selected wallpaper and keep the launcher open'
complete -c inir -n '__inir_at_function wallpaperLauncher wallpaper-launcher' -a status -d 'Return launcher mode, index, count, path, target and monito…'
complete -c inir -n '__inir_at_target' -a wallpaperSelector -d 'Wallpaper picker with grid, coverflow and compact launcher…'
complete -c inir -n '__inir_at_target' -a wallpaper-selector -d 'Wallpaper picker with grid, coverflow and compact launcher…'
complete -c inir -n '__inir_at_function wallpaperSelector wallpaper-selector' -a toggle -d 'Open/close wallpaper selector'
complete -c inir -n '__inir_at_function wallpaperSelector wallpaper-selector' -a open -d 'Open wallpaper selector'
complete -c inir -n '__inir_at_function wallpaperSelector wallpaper-selector' -a close -d 'Close wallpaper selector'
complete -c inir -n '__inir_at_function wallpaperSelector wallpaper-selector' -a openLauncher -d 'Open the compact launcher in static or animated mode'
complete -c inir -n '__inir_at_value 1 openLauncher wallpaperSelector wallpaper-selector' -a 'static animated'
complete -c inir -n '__inir_at_function wallpaperSelector wallpaper-selector' -a toggleOnMonitor -d 'Open wallpaper selector on a specific monitor'
complete -c inir -n '__inir_at_function wallpaperSelector wallpaper-selector' -a random -d 'Pick a random wallpaper from the current folder'
complete -c inir -n '__inir_at_function wallpaperSelector wallpaper-selector' -a next -d 'Next wallpaper as the desktop menu does it: from the curren…'
complete -c inir -n '__inir_at_function wallpaperSelector wallpaper-selector' -a shuffle -d 'A new wallpaper from the folder every few minutes: on, off,…'
complete -c inir -n '__inir_at_value 1 shuffle wallpaperSelector wallpaper-selector' -a 'on off status'
complete -c inir -n '__inir_at_function wallpaperSelector wallpaper-selector' -a set -d 'Apply a wallpaper (picture, GIF or video) by path, the same…'
complete -c inir -n '__inir_at_function wallpaperSelector wallpaper-selector' -a preview -d 'Show a wallpaper on the desktop without applying it: no con…'
complete -c inir -n '__inir_at_function wallpaperSelector wallpaper-selector' -a cancelPreview -d 'Drop the preview and go back to the applied wallpaper'
complete -c inir -n '__inir_at_function wallpaperSelector wallpaper-selector' -a browse -d 'Open the picker on a source — library, wallhaven or live (a…'
complete -c inir -n '__inir_at_value 2 browse wallpaperSelector wallpaper-selector' -a 'library wallhaven live'
complete -c inir -n '__inir_at_function wallpaperSelector wallpaper-selector' -a kind -d 'Show only one kind of wallpaper in the library: all, still,…'
complete -c inir -n '__inir_at_value 1 kind wallpaperSelector wallpaper-selector' -a 'all still live gif'
complete -c inir -n '__inir_at_function wallpaperSelector wallpaper-selector' -a move -d 'Move the gallery\'s selection by that many tiles, as the arr…'
complete -c inir -n '__inir_at_function wallpaperSelector wallpaper-selector' -a status -d 'Return picker style, open surface, target monitor and selec…'
complete -c inir -n '__inir_at_target' -a wbar -d 'Waffle taskbar visibility'
complete -c inir -n '__inir_at_function wbar' -a toggle -d 'Show/hide taskbar'
complete -c inir -n '__inir_at_function wbar' -a close -d 'Hide taskbar'
complete -c inir -n '__inir_at_function wbar' -a open -d 'Show taskbar'
complete -c inir -n '__inir_at_target' -a widgetStacks -d 'iRiS widget stacks: several desktop widgets sharing one pla…'
complete -c inir -n '__inir_at_target' -a widget-stacks -d 'iRiS widget stacks: several desktop widgets sharing one pla…'
complete -c inir -n '__inir_at_function widgetStacks widget-stacks' -a status -d 'Returns JSON: whether stacks are live, each stack\'s id, pag…'
complete -c inir -n '__inir_at_function widgetStacks widget-stacks' -a create -d 'Stack two or more iRiS widgets joined with + (weather+month…'
complete -c inir -n '__inir_at_value 1 create widgetStacks widget-stacks' -a 'weather+monthCalendar'
complete -c inir -n '__inir_at_function widgetStacks widget-stacks' -a add -d 'Add a widget as the last page'
complete -c inir -n '__inir_at_function widgetStacks widget-stacks' -a remove -d 'Take a widget out; it stays where the stack is and the layo…'
complete -c inir -n '__inir_at_function widgetStacks widget-stacks' -a dissolve -d 'Split the stack back into single widgets'
complete -c inir -n '__inir_at_function widgetStacks widget-stacks' -a page -d 'Show a page: a widget name, next or previous'
complete -c inir -n '__inir_at_value 2 page widgetStacks widget-stacks' -a 'next previous'
complete -c inir -n '__inir_at_function widgetStacks widget-stacks' -a move -d 'Move a page earlier (-1) or later (1) in the order'
complete -c inir -n '__inir_at_function widgetStacks widget-stacks' -a rotate -d 'on or off: the stack turns its own pages'
complete -c inir -n '__inir_at_value 2 rotate widgetStacks widget-stacks' -a 'on off'
complete -c inir -n '__inir_at_function widgetStacks widget-stacks' -a interval -d 'Seconds between turns (5 to 3600)'
complete -c inir -n '__inir_at_target' -a widgetpower -d 'Desktop-widget power management (pauses widget rendering on…'
complete -c inir -n '__inir_at_function widgetpower' -a status -d 'Returns JSON: enabled, widgetsActive, pauseReason, and the…'
complete -c inir -n '__inir_at_target' -a wnotificationCenter -d 'Waffle notification center'
complete -c inir -n '__inir_at_target' -a wnotification-center -d 'Waffle notification center'
complete -c inir -n '__inir_at_function wnotificationCenter wnotification-center' -a toggle -d 'Open/close notification center'
complete -c inir -n '__inir_at_function wnotificationCenter wnotification-center' -a close -d 'Close notification center'
complete -c inir -n '__inir_at_function wnotificationCenter wnotification-center' -a open -d 'Open notification center'
complete -c inir -n '__inir_at_target' -a workspaceStrip -d 'Workspace edge strip'
complete -c inir -n '__inir_at_target' -a workspace-strip -d 'Workspace edge strip'
complete -c inir -n '__inir_at_function workspaceStrip workspace-strip' -a open -d 'Keep the strip expanded'
complete -c inir -n '__inir_at_function workspaceStrip workspace-strip' -a close -d 'Return the strip to hover/peek mode'
complete -c inir -n '__inir_at_function workspaceStrip workspace-strip' -a toggle -d 'Toggle forced expansion'
complete -c inir -n '__inir_at_function workspaceStrip workspace-strip' -a status -d 'Return strip state (open or auto)'
complete -c inir -n '__inir_at_target' -a wwidgets -d 'Waffle widgets panel'
complete -c inir -n '__inir_at_function wwidgets' -a toggle -d 'Open/close widgets'
complete -c inir -n '__inir_at_function wwidgets' -a close -d 'Close widgets'
complete -c inir -n '__inir_at_function wwidgets' -a open -d 'Open widgets'
complete -c inir -n '__inir_at_target' -a ytmusic -d 'Direct YtMusic player control'
complete -c inir -n '__inir_at_function ytmusic' -a playPause -d 'Toggle YtMusic play/pause'
complete -c inir -n '__inir_at_function ytmusic' -a next -d 'Play next track in YtMusic'
complete -c inir -n '__inir_at_function ytmusic' -a previous -d 'Play previous track in YtMusic'
complete -c inir -n '__inir_at_function ytmusic' -a stop -d 'Stop YtMusic playback'
complete -c inir -n '__inir_at_target' -a zoom -d 'Screen zoom'
complete -c inir -n '__inir_at_function zoom' -a zoomIn -d 'Increase compositor zoom'
complete -c inir -n '__inir_at_function zoom' -a zoomOut -d 'Decrease compositor zoom'
# <<< generated from the IPC registry <<<
